apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-hello-world
  template:
    metadata:
      labels:
        app: flask-hello-world
    spec:
      containers:
        - name: flask-hello-world
          image: hello-world-from-flask:v2
          imagePullPolicy: IfNotPresent  # By default, Kubernetes will always try to pull an image with the tag latest.
          # By specifying an image pull policy of IfNotPresent, Kubernetes will only pull the image if it doesn't already exist locally.
          ports:
            - containerPort: 8080
