apiVersion: v1
kind: Service
metadata:
  name: flask-hello-world-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30007 # Optional: Specify a nodePort in the range (30000-32767) if you want a specific port
  selector:
    app: flask-hello-world
